//
//  SearchWireframe.swift
//  epam_star_wars_hard
//
//  Created by Nickolay Truhin on 18.02.2020.
//  Copyright (c) 2020 Nickolay Truhin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchWireframe: BaseWireframe {
    
    // MARK: - Private properties -
    
    private let storyboard = UIStoryboard(name: "Search", bundle: nil)
    
    // MARK: - Module setup -
    
    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: SearchViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = SearchInteractor()
        let presenter = SearchPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
    
}

// MARK: - Extensions -

extension SearchWireframe: SearchWireframeInterface {
    
    func navigate(to option: SearchNavigationOption) {
        switch option {
        case .details(let people):
            _openDetails(with: people)
        }
    }
    
    private func _openDetails(with people: People) {
        navigationController?.pushWireframe(DetailsWireframe(people: people))
    }
    
}
