//
//  SearchWireframe.swift
//  epam_star_wars_hard
//
//  Created by Nickolay Truhin on 18.02.2020.
//  Copyright (c) 2020 Nickolay Truhin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = SearchViewController()
        super.init(viewController: moduleViewController)

        let interactor = SearchInteractor()
        let presenter = SearchPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SearchWireframe: SearchWireframeInterface {
    
    func navigate(to option: SearchNavigationOption) {
        switch option {
        case .details:
            _presentDetails()
        }

    }
    
    private func _presentDetails() {
//        let wireframe = DetailsWireframe()

//        let wireframeNavigationController = StarWarsNavigationController()
//        wireframeNavigationController.setRootWireframe(wireframe)
//
//        navigationController?.present(wireframeNavigationController, animated: true, completion: nil)

    }
    
}
