//
//  SearchInterfaces.swift
//  epam_star_wars_hard
//
//  Created by Nickolay Truhin on 18.02.2020.
//  Copyright (c) 2020 Nickolay Truhin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
//import Alamofire

enum SearchNavigationOption {
    case details
}

protocol SearchWireframeInterface: WireframeInterface {
}

protocol SearchViewInterface: ViewInterface {
}

protocol SearchPresenterInterface: PresenterInterface {
//    func didSearchSubmitted(_ query: String)
}

protocol SearchInteractorInterface: InteractorInterface {
//    @discardableResult
//    func searchCharacters(_ query: String, _ completion: @escaping PeopleResponseCompletionBlock) -> DataRequest
}
