//
//  DetailsInteractor.swift
//  epam_star_wars_hard
//
//  Created by Nickolay Truhin on 20.02.2020.
//  Copyright (c) 2020 Nickolay Truhin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailsInteractor {
}

// MARK: - Extensions -

extension DetailsInteractor: DetailsInteractorInterface {
}
