//
//  DetailsWireframe.swift
//  epam_star_wars_hard
//
//  Created by Nickolay Truhin on 20.02.2020.
//  Copyright (c) 2020 Nickolay Truhin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Details", bundle: nil)

    // MARK: - Module setup -

    init(people: People) {
        let moduleViewController = storyboard.instantiateViewController(ofType: DetailsViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = DetailsInteractor()
        let presenter = DetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, model: people)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailsWireframe: DetailsWireframeInterface {
}
