//
//  DetailsInterfaces.swift
//  epam_star_wars_hard
//
//  Created by Nickolay Truhin on 20.02.2020.
//  Copyright (c) 2020 Nickolay Truhin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailsWireframeInterface: WireframeInterface {
}

protocol DetailsViewInterface: ViewInterface {
}

protocol DetailsPresenterInterface: PresenterInterface {
    func numberOfItems() -> Int
    func item(at indexPath: IndexPath) -> (key: String, value: String)
}

protocol DetailsInteractorInterface: InteractorInterface {
}
